from engine.middleware.llm import PerplexityLLMService
import asyncio
import os
import logging
from engine.middleware.planner import Planner
from engine.middleware.llm import LLMService
from engine.agents.hawk import HawkAgent
from engine.agents.biologist import BiologistAgent
from engine.agents.librarian import LibrarianAgent
from engine.orchestrator import Orchestrator
from engine.middleware.synthesizer import ReportSynthesizer

try:
    from dotenv import load_dotenv
    # Load environment variables
    load_dotenv()
    load_dotenv("engine/.env")
except ImportError:
    print("Warning: python-dotenv not installed. Relying on system environment variables.")

# Setup basic logging
logging.basicConfig(level=logging.INFO)

class MockLLM(LLMService):
    """Mock LLM to avoid API costs during verification and deterministic testing."""
    def __init__(self):
        pass
        
    def generate(self, prompt: str, system_prompt: str = None, temperature: float = 0.0) -> str:
        # Simple mock Plan response
        if "Keytruda" in prompt:
            return '''```json
            [
                {"agent": "Hawk", "function": "check_safety", "args": {"drug_name": "Keytruda"}},
                {"agent": "Librarian", "function": "search_literature", "args": {"disease": "Pembrolizumab", "year": 2024}}
            ]
            ```'''
        elif "EGFR" in prompt:
             return '''```json
            [
                {"agent": "Biologist", "function": "validate_target", "args": {"gene_symbol": "EGFR"}}
            ]
            ```'''
        # Mock Report response (if synthesizer calls this)
        if "Context Data" in prompt:
            return r"""\documentclass{article}
\usepackage{geometry}
\usepackage{hyperref}
\title{Mock Report on EGFR}
\author{Entropy Engine}
\begin{document}
\maketitle
\section{Introduction}
This is a mock report generated by MockLLM. According to \href{https://platform.opentargets.org/target/ENSG00000146648}{Biologist}, EGFR is a key target.
\section{References}
\begin{itemize}
    \item EGFR Target Validation - \href{https://platform.opentargets.org/target/ENSG00000146648}{Open Targets}
    \item Keytruda Safety - \href{https://open.fda.gov/drug/label?search=openfda.brand_name:Keytruda}{FDA Label}
\end{itemize}
\end{document}"""
            
        return "[]"

async def main():
    print("--- Initializing Components ---")
    
    # 1. Initialize Mocks/Real Components
    # We use MockLLM for the planner to ensure we get a valid plan without hitting an LLM API
    # To fully test Synthesizer with Perplexity, we should use PerplexityLLMService if key is available,
    # or fallback to MockLLM if not (or if desired to save credits).
    # For this verification run, I'll use the MockLLM for Planner to get predictable plans,
    # and MockLLM for Synthesizer to verify wiring unless I want to test actual PPLX generation.
    # Given the user probably wants to see wiring work first, I'll use MockLLM for consistent testing of wiring.
    # If the user explicitly wants to see PPLX output, we'd switch.
    
    # mock_llm = MockLLM() 
    # NOTE: Uncomment below to use real Perplexity if API Key is set
    real_llm = PerplexityLLMService(api_key=os.getenv("PERPLEXITY_API_KEY"))
    
    planner = Planner(llm_service=real_llm)
    synthesizer = ReportSynthesizer(llm_service=real_llm) 
    
    # We use real agents (assuming they can handle requests or fail gracefully if no API keys)
    hawk = HawkAgent()
    biologist = BiologistAgent()
    librarian = LibrarianAgent()
    
    orchestrator = Orchestrator(planner, hawk, biologist, librarian, synthesizer)
    
    # 2. Test Case 1: Keytruda
    query = "Is EGFR safe and what are recent papers?"
    print(f"\n--- Processing Query: {query} ---")
    result = await orchestrator.process_query(query)
    
    print("\n--- Execution Results ---")
    import json
    # Print just the summaries/keys to avoid flooding terminal
    print(f"Results Count: {len(result['results'])}")
    
    print("\n--- Final Report Info ---")
    report_info = result.get("report", {})
    if isinstance(report_info, dict):
        print(f"Content length: {len(report_info.get('report_content', ''))}")
        print(f"TeX Path: {report_info.get('tex_path')}")
        print(f"PDF Path: {report_info.get('pdf_path')}")
        
        # Verify File Existence
        if report_info.get('tex_path') and os.path.exists(report_info.get('tex_path')):
             print("SUCCESS: .tex file created.")
        else:
             print("FAILURE: .tex file NOT created.")

        if report_info.get('pdf_path') and os.path.exists(report_info.get('pdf_path')):
             print("SUCCESS: .pdf file created.")
        else:
             print("INFO: .pdf file NOT created (Expected if pdflatex is missing).")
    else:
        print(f"Report: {report_info}")
    
    # 3. Cleanup
    await hawk.close()
    await biologist.close()
    await librarian.close()

if __name__ == "__main__":
    asyncio.run(main())
