import { escapeLatex } from "./latex-escape.js";
import type { ReportInput } from "./types.js";

/**
 * Extracts citation-like references (DOIs, PMIDs, URLs) from text.
 * Returns an array of { key, ref } objects for the bibliography.
 */
export function extractCitations(
  text: string,
): Array<{ key: string; ref: string }> {
  const citations: Array<{ key: string; ref: string }> = [];

  // Match DOIs: 10.XXXX/...
  const doiRegex = /\b(10\.\d{4,}\/[^\s,;)\]]+)/g;
  let m: RegExpExecArray | null;
  while ((m = doiRegex.exec(text)) !== null) {
    const doi = m[1];
    const key = "doi:" + doi.replace(/[^a-zA-Z0-9]/g, "_");
    if (!citations.find((c) => c.key === key)) {
      citations.push({ key, ref: `DOI: \\url{${doi}}` });
    }
  }

  // Match PMIDs: PMID: XXXXXXXX
  const pmidRegex = /PMID[:\s]+(\d{6,9})/gi;
  while ((m = pmidRegex.exec(text)) !== null) {
    const pmid = m[1];
    const key = "pmid:" + pmid;
    if (!citations.find((c) => c.key === key)) {
      citations.push({
        key,
        ref: `PubMed ID: ${pmid}. \\url{https://pubmed.ncbi.nlm.nih.gov/${pmid}/}`,
      });
    }
  }

  // Match URLs (http/https)
  const urlRegex = /https?:\/\/[^\s,;)\]>\"]+/g;
  while ((m = urlRegex.exec(text)) !== null) {
    const url = m[0].replace(/[.,;)\]]+$/, ""); // strip trailing punctuation
    const key = "url:" + url.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 40);
    if (!citations.find((c) => c.key === key)) {
      citations.push({ key, ref: `\\url{${url}}` });
    }
  }

  return citations;
}

/** Collect all citations from the report input */
export function collectAllCitations(
  input: ReportInput,
): Array<{ key: string; ref: string }> {
  const allText = [
    input.evidence.agents.biologist.content,
    input.evidence.agents.clinicalScout.content,
    input.evidence.agents.hawk.content,
    input.evidence.agents.librarian.content,
    input.verificationReport.summary,
    input.gapAnalysis.summary,
  ].join("\n");

  return extractCitations(allText);
}

/** Insert \cite{key} commands for DOIs/PMIDs in content */
function inlineCitations(
  text: string,
  citations: Array<{ key: string; ref: string }>,
): string {
  let result = text;
  for (const { key, ref } of citations) {
    // Try to match the original identifier back from ref
    const doiMatch = ref.match(/DOI: \\url\{([^}]+)\}/);
    const pmidMatch = ref.match(/PubMed ID: (\d+)/);
    const urlMatch = ref.match(/\\url\{([^}]+)\}/);

    if (doiMatch) {
      result = result.replace(
        new RegExp(escapeRegex(doiMatch[1]), "g"),
        `$& \\cite{${key}}`,
      );
    } else if (pmidMatch) {
      result = result.replace(
        new RegExp(`PMID[:\\s]+${pmidMatch[1]}`, "gi"),
        `$& \\cite{${key}}`,
      );
    } else if (urlMatch) {
      result = result.replace(
        new RegExp(escapeRegex(urlMatch[1]), "g"),
        `$& \\cite{${key}}`,
      );
    }
  }
  return result;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ─── Section Generators ───────────────────────────────────────────────────────

export function titlePageSection(input: ReportInput): string {
  const title = escapeLatex(input.query);
  const timestamp = escapeLatex(input.metadata.timestamp);
  const sessionId = escapeLatex(input.metadata.sessionId ?? "N/A");
  const reviewer = escapeLatex(input.reviewerDecision.reviewer);

  return `\\begin{titlepage}
\\centering
{\\Huge\\bfseries Drug Repurposing Dossier\\par}
\\vspace{1cm}
{\\Large\\bfseries ${title}\\par}
\\vspace{2cm}
{\\large
  \\textbf{Timestamp:} ${timestamp}\\\\[0.5em]
  \\textbf{Session ID:} ${sessionId}\\\\[0.5em]
  \\textbf{Reviewer:} ${reviewer}\\\\[0.5em]
}
\\vfill
{\\small Generated by Entropy Research Pipeline}
\\end{titlepage}`;
}

export function executiveSummarySection(input: ReportInput): string {
  const verSummary = escapeLatex(input.verificationReport.summary);
  const gapSummary = escapeLatex(input.gapAnalysis.summary);

  return `\\section{Executive Summary}

\\subsection{Verification Summary}
${verSummary}

\\subsection{Gap Analysis Summary}
${gapSummary}`;
}

export function ppicoSection(input: ReportInput): string {
  const { population, intervention, comparison, outcome } =
    input.evidence.ppicoBreakdown;

  return `\\section{PPICO Breakdown}

\\begin{description}
  \\item[Population] ${escapeLatex(population)}
  \\item[Intervention] ${escapeLatex(intervention)}
  \\item[Comparison] ${escapeLatex(comparison)}
  \\item[Outcome] ${escapeLatex(outcome)}
\\end{description}`;
}

export function biologicalRationaleSection(
  input: ReportInput,
  citations: Array<{ key: string; ref: string }>,
): string {
  const content = inlineCitations(
    escapeLatex(input.evidence.agents.biologist.content),
    citations,
  );
  return `\\section{Biological Rationale}

${content}`;
}

export function clinicalLandscapeSection(
  input: ReportInput,
  citations: Array<{ key: string; ref: string }>,
): string {
  const content = inlineCitations(
    escapeLatex(input.evidence.agents.clinicalScout.content),
    citations,
  );
  return `\\section{Clinical Landscape}

${content}`;
}

export function safetyProfileSection(
  input: ReportInput,
  citations: Array<{ key: string; ref: string }>,
): string {
  const content = inlineCitations(
    escapeLatex(input.evidence.agents.hawk.content),
    citations,
  );
  return `\\section{Safety Profile}

${content}`;
}

export function literatureReviewSection(
  input: ReportInput,
  citations: Array<{ key: string; ref: string }>,
): string {
  const content = inlineCitations(
    escapeLatex(input.evidence.agents.librarian.content),
    citations,
  );
  return `\\section{Literature Review}

${content}`;
}

export function gapAnalysisSection(input: ReportInput): string {
  const ga = input.gapAnalysis;

  // TPP checklist table
  const rows = ga.tppChecklist
    .map(
      (item) =>
        `  ${escapeLatex(item.category)} & ${escapeLatex(item.status)} & ${escapeLatex(item.notes)} \\\\`,
    )
    .join("\n");

  const tppTable =
    ga.tppChecklist.length > 0
      ? `\\subsection{TPP Checklist}
\\begin{tabular}{|l|c|p{8cm}|}
\\hline
\\textbf{Category} & \\textbf{Status} & \\textbf{Notes} \\\\
\\hline
${rows}
\\hline
\\end{tabular}`
      : `\\subsection{TPP Checklist}\nNo checklist items.`;

  // Present evidence
  const presentEvidence =
    ga.presentEvidence.length > 0
      ? ga.presentEvidence
          .map(
            (e) =>
              `  \\item \\textbf{${escapeLatex(e.category)}} (${escapeLatex(e.strength)}): ${escapeLatex(e.description)}`,
          )
          .join("\n")
      : "  \\item None";

  // Missing evidence
  const missingEvidence =
    ga.missingEvidence.length > 0
      ? ga.missingEvidence
          .map(
            (g) =>
              `  \\item \\textbf{${escapeLatex(g.category)}} [${escapeLatex(g.severity)}]: ${escapeLatex(g.description)} --- \\textit{${escapeLatex(g.recommendation)}}`,
          )
          .join("\n")
      : "  \\item None";

  // Contradictions
  const contradictions =
    ga.contradictions.length > 0
      ? ga.contradictions
          .map(
            (c) =>
              `  \\item [${escapeLatex(c.severity)}] ${escapeLatex(c.description)} (${escapeLatex(c.sourceA.agentId)} vs ${escapeLatex(c.sourceB.agentId)})`,
          )
          .join("\n")
      : "  \\item None";

  // Risk flags
  const riskFlags =
    ga.riskFlags.length > 0
      ? ga.riskFlags
          .map(
            (r) =>
              `  \\item \\textbf{${escapeLatex(r.flag)}} [${escapeLatex(r.severity)}]: ${escapeLatex(r.description)}`,
          )
          .join("\n")
      : "  \\item None";

  return `\\section{Gap Analysis}

${tppTable}

\\subsection{Present Evidence}
\\begin{itemize}
${presentEvidence}
\\end{itemize}

\\subsection{Missing Evidence}
\\begin{itemize}
${missingEvidence}
\\end{itemize}

\\subsection{Contradictions}
\\begin{itemize}
${contradictions}
\\end{itemize}

\\subsection{Risk Flags}
\\begin{itemize}
${riskFlags}
\\end{itemize}

\\subsection{Overall Readiness}
${escapeLatex(ga.overallReadiness)}`;
}

export function verificationReportSection(input: ReportInput): string {
  const vr = input.verificationReport;

  const claimRows = vr.claims
    .map(
      (c) =>
        `  ${escapeLatex(c.claimId)} & ${escapeLatex(c.verificationStatus)} & ${(c.confidence * 100).toFixed(0)}\\% & ${escapeLatex(c.discrepancy ?? "---")} \\\\`,
    )
    .join("\n");

  const claimsTable =
    vr.claims.length > 0
      ? `\\begin{tabular}{|l|c|c|p{6cm}|}
\\hline
\\textbf{Claim ID} & \\textbf{Status} & \\textbf{Confidence} & \\textbf{Discrepancy} \\\\
\\hline
${claimRows}
\\hline
\\end{tabular}`
      : "No claims checked.";

  return `\\section{Verification Report}

\\textbf{Overall Integrity:} ${escapeLatex(vr.overallIntegrity)}\\\\
\\textbf{Total Claims Checked:} ${vr.totalClaimsChecked}\\\\
\\textbf{Confirmed:} ${vr.confirmedCount}\\\\
\\textbf{Flagged:} ${vr.flaggedCount}\\\\
\\textbf{Unverifiable:} ${vr.unverifiableCount}

\\subsection{Claims Table}
${claimsTable}`;
}

export function reviewerDecisionSection(input: ReportInput): string {
  const rd = input.reviewerDecision;
  const status = rd.approved
    ? "\\textcolor{green}{APPROVED}"
    : "\\textcolor{red}{REJECTED}";

  return `\\section{Reviewer Decision}

\\textbf{Decision:} ${status}\\\\
\\textbf{Reviewer:} ${escapeLatex(rd.reviewer)}\\\\
\\textbf{Notes:} ${escapeLatex(rd.notes)}`;
}

export function appendicesSection(input: ReportInput): string {
  const gaRecs =
    input.gapAnalysis.recommendations.length > 0
      ? input.gapAnalysis.recommendations
          .map((r) => `  \\item ${escapeLatex(r)}`)
          .join("\n")
      : "  \\item None";

  const vrRecs =
    input.verificationReport.recommendations.length > 0
      ? input.verificationReport.recommendations
          .map((r) => `  \\item ${escapeLatex(r)}`)
          .join("\n")
      : "  \\item None";

  return `\\appendix

\\section{Gap Analysis Recommendations}
\\begin{enumerate}
${gaRecs}
\\end{enumerate}

\\section{Verification Report Recommendations}
\\begin{enumerate}
${vrRecs}
\\end{enumerate}`;
}

export function bibliographySection(
  citations: Array<{ key: string; ref: string }>,
): string {
  if (citations.length === 0) {
    return `\\begin{thebibliography}{0}
\\end{thebibliography}`;
  }

  const items = citations
    .map((c, i) => `\\bibitem{${c.key}}\n  ${c.ref}`)
    .join("\n\n");

  return `\\begin{thebibliography}{${citations.length}}
${items}
\\end{thebibliography}`;
}
